// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PayrollCalc.Infrastructure.Data;

#nullable disable

namespace PayrollCalc.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511172716_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PayrollCalc.Core.Entities.AvgSalaryInclusionRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IncludeCompensation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeSick")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeTraining")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeVacation")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AvgSalaryInclusionRules");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Calculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllowancesTotal")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Esv")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GpdTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("numeric");

                    b.Property<decimal>("JSalary")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ManualTotal")
                        .HasColumnType("numeric");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("NSalary")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("numeric");

                    b.Property<string>("ParamsSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Pdfo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PkrTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SickEmployer")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SickFss")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TrainingAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnionFee")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VacationAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Vz")
                        .HasColumnType("numeric");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Calculations");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.CalculationPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bonus1749Pct")
                        .HasColumnType("numeric");

                    b.Property<int>("CalculationId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date");

                    b.Property<decimal>("MonthlyRate")
                        .HasColumnType("numeric");

                    b.Property<int>("WorkDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CalculationId");

                    b.ToTable("CalculationPeriods");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DismissalDate")
                        .HasColumnType("date");

                    b.Property<string>("Education")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<int>("PedExperienceYears")
                        .HasColumnType("integer");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TabNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TitleTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkerClass")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("TitleTypeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeAdmin", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AdminRateCount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DirectorPct")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PedRateCount")
                        .HasColumnType("numeric");

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeeAdmins");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeAllowances", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int?>("CabinetType")
                        .HasColumnType("integer");

                    b.Property<int?>("ClassGradeGroup")
                        .HasColumnType("integer");

                    b.Property<bool>("HasCabinet")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasClassMgmt")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasComputers")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasExtracurricular")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasGym")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasLibraryMgmt")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasMentor")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasMilitaryAcct")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasShootingRange")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasTextbooks")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasUnfavorable")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasWebsite")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LibraryMgmtAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MentorAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TextbooksAmount")
                        .HasColumnType("numeric");

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeeAllowances");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeBase", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RateCount")
                        .HasColumnType("numeric");

                    b.Property<int>("TariffGradeId")
                        .HasColumnType("integer");

                    b.HasKey("EmployeeId");

                    b.HasIndex("TariffGradeId");

                    b.ToTable("EmployeeBases");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeGpd", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("GpdHours")
                        .HasColumnType("numeric");

                    b.Property<int>("TariffGradeId")
                        .HasColumnType("integer");

                    b.HasKey("EmployeeId");

                    b.HasIndex("TariffGradeId");

                    b.ToTable("EmployeeGpds");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeNonPedagogical", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasDisinfectants")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasNightShifts")
                        .HasColumnType("boolean");

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeeNonPedagogical");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeePkr", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PkrHours")
                        .HasColumnType("numeric");

                    b.Property<int>("TariffGradeId")
                        .HasColumnType("integer");

                    b.HasKey("EmployeeId");

                    b.HasIndex("TariffGradeId");

                    b.ToTable("EmployeePkrs");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeWorkload", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Hours10To11")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Hours1To4")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Hours5To9")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InclusiveHours1To4")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InclusiveHours5To9")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IndividualHours10To11")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IndividualHours1To4")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IndividualHours5To9")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NotebookHours10To11")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NotebookHours1To4")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NotebookHours5To9")
                        .HasColumnType("numeric");

                    b.Property<int>("NotebookRateId")
                        .HasColumnType("integer");

                    b.HasKey("EmployeeId");

                    b.HasIndex("NotebookRateId");

                    b.ToTable("EmployeeWorkloads");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EnforcementDeduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EnforcementDeductions");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.NotebookRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Pct")
                        .HasColumnType("numeric");

                    b.Property<string>("SubjectKeyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NotebookRates");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkerClass")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.SickLeave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountEmployer")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AmountFss")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AverageDaily")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("BaseCalculationMode")
                        .HasColumnType("integer");

                    b.Property<int>("BaseDays")
                        .HasColumnType("integer");

                    b.Property<int>("BaseExcludedDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DaysEmployer")
                        .HasColumnType("integer");

                    b.Property<int>("DaysFss")
                        .HasColumnType("integer");

                    b.Property<int>("DaysTotal")
                        .HasColumnType("integer");

                    b.Property<string>("EfssNumber")
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("InsuranceSeniorityYrs")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("PaymentPct")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SickLeaves");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.SystemParam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SystemParams");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.TariffGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyRate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("TariffGrades");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Timesheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Advance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AnnualBonus")
                        .HasColumnType("numeric");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("EnforcementOrders")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HolidayAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("NightHours")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OtherManual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Recalculation")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ReplacementHours")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WorkedDays")
                        .HasColumnType("numeric");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Timesheets");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.TitleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Pct")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("TitleTypes");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.TrainingLeave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageDaily")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("BaseCalculationMode")
                        .HasColumnType("integer");

                    b.Property<int>("BaseWorkingDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("InstitutionName")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("WorkingDaysAbsent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TrainingLeaves");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Vacation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AverageDaily")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BaseAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("BaseCalculationMode")
                        .HasColumnType("integer");

                    b.Property<int?>("BaseDays")
                        .HasColumnType("integer");

                    b.Property<int>("CalendarDays")
                        .HasColumnType("integer");

                    b.Property<int?>("CarryOverMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("CarryOverYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCarryOver")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("VacationType")
                        .HasColumnType("integer");

                    b.Property<int>("WorkingDaysAbsent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Vacations");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.WorkCalendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("WorkDays")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WorkCalendars");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Calculation", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.CalculationPeriod", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Calculation", "Calculation")
                        .WithMany("Periods")
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calculation");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Employee", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollCalc.Core.Entities.TitleType", "TitleType")
                        .WithMany()
                        .HasForeignKey("TitleTypeId");

                    b.Navigation("Position");

                    b.Navigation("TitleType");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeAdmin", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithOne("Admin")
                        .HasForeignKey("PayrollCalc.Core.Entities.EmployeeAdmin", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeAllowances", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithOne("Allowances")
                        .HasForeignKey("PayrollCalc.Core.Entities.EmployeeAllowances", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeBase", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithOne("Base")
                        .HasForeignKey("PayrollCalc.Core.Entities.EmployeeBase", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollCalc.Core.Entities.TariffGrade", "TariffGrade")
                        .WithMany()
                        .HasForeignKey("TariffGradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TariffGrade");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeGpd", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithOne("Gpd")
                        .HasForeignKey("PayrollCalc.Core.Entities.EmployeeGpd", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollCalc.Core.Entities.TariffGrade", "TariffGrade")
                        .WithMany()
                        .HasForeignKey("TariffGradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TariffGrade");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeNonPedagogical", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithOne("NonPedagogical")
                        .HasForeignKey("PayrollCalc.Core.Entities.EmployeeNonPedagogical", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeePkr", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithOne("Pkr")
                        .HasForeignKey("PayrollCalc.Core.Entities.EmployeePkr", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollCalc.Core.Entities.TariffGrade", "TariffGrade")
                        .WithMany()
                        .HasForeignKey("TariffGradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TariffGrade");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeWorkload", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithOne("Workload")
                        .HasForeignKey("PayrollCalc.Core.Entities.EmployeeWorkload", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollCalc.Core.Entities.NotebookRate", "NotebookRate")
                        .WithMany()
                        .HasForeignKey("NotebookRateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("NotebookRate");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EnforcementDeduction", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Position", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.SickLeave", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Timesheet", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.TrainingLeave", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Vacation", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Calculation", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Employee", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Allowances");

                    b.Navigation("Base");

                    b.Navigation("Gpd");

                    b.Navigation("NonPedagogical");

                    b.Navigation("Pkr");

                    b.Navigation("Workload");
                });
#pragma warning restore 612, 618
        }
    }
}
