// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PayrollCalc.Infrastructure.Data;

#nullable disable

namespace PayrollCalc.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PayrollCalc.Core.Entities.AvgSalaryInclusionRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IncludeCompensation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeSick")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeTraining")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeVacation")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FieldKey")
                        .IsUnique();

                    b.ToTable("AvgSalaryInclusionRules");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Calculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllowancesTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Esv")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("GpdTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("GrossSalary")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("JSalary")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("ManualTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("NSalary")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("NetSalary")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ParamsSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("Pdfo")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("PkrTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("SickEmployer")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("SickFss")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TrainingAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("UnionFee")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("VacationAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Vz")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("Calculations");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.CalculationComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("CalculationId")
                        .HasColumnType("integer");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CalculationId");

                    b.ToTable("CalculationComponents");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.CalculationPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bonus1749Pct")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("CalculationId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date");

                    b.Property<decimal>("MonthlyRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("WorkDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CalculationId");

                    b.ToTable("CalculationPeriods");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DismissalDate")
                        .HasColumnType("date");

                    b.Property<string>("Education")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GeneralExperienceYears")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("HonoredAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<bool>("IsHonored")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUnionMember")
                        .HasColumnType("boolean");

                    b.Property<int>("PedExperienceYears")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SocialBenefitPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TabNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("TaxId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeAdmin", b =>
                {
                    b.Property<int>("EmployeePositionId")
                        .HasColumnType("integer");

                    b.Property<int?>("CabinetType")
                        .HasColumnType("integer");

                    b.Property<int?>("ClassGradeGroup")
                        .HasColumnType("integer");

                    b.Property<bool>("HasCabinet")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasClassMgmt")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasComputers")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasExtracurricular")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasGym")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasShootingRange")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasWebsite")
                        .HasColumnType("boolean");

                    b.HasKey("EmployeePositionId");

                    b.ToTable("EmployeeAdmins");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeGpd", b =>
                {
                    b.Property<int>("EmployeePositionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("GpdRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("TariffGradeId")
                        .HasColumnType("integer");

                    b.HasKey("EmployeePositionId");

                    b.HasIndex("TariffGradeId");

                    b.ToTable("EmployeeGpds");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeNonPedagogical", b =>
                {
                    b.Property<int>("EmployeePositionId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasDisinfectants")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasLibraryMgmt")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasMentor")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasNightShifts")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasTextbooks")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LibraryMgmtAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("MentorAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("TextbooksAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("EmployeePositionId");

                    b.ToTable("EmployeeNonPedagogical");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeePkr", b =>
                {
                    b.Property<int>("EmployeePositionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PkrHours")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("TariffGradeId")
                        .HasColumnType("integer");

                    b.HasKey("EmployeePositionId");

                    b.HasIndex("TariffGradeId");

                    b.ToTable("EmployeePkrs");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeePosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ComplexityBonusPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("DirectorPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateOnly?>("DismissalDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasUnfavorable")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<bool>("MaintainsMilitaryRecords")
                        .HasColumnType("boolean");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("PositionStartDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("PrestigeBonusPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("RateCount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("TariffGradeId")
                        .HasColumnType("integer");

                    b.Property<int?>("TitleTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("TariffGradeId");

                    b.HasIndex("TitleTypeId");

                    b.HasIndex("EmployeeId", "PositionId")
                        .IsUnique()
                        .HasFilter("\"DismissalDate\" IS NULL");

                    b.ToTable("EmployeePositions");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeWorkload", b =>
                {
                    b.Property<int>("EmployeePositionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AdditionalHours")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Hours10To11")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Hours1To4")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Hours5To9")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("InclusiveHours10To11")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("InclusiveHours1To4")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("InclusiveHours5To9")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("IndividualHours10To11")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("IndividualHours1To4")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("IndividualHours5To9")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("NotebookHours10To11")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("NotebookHours1To4")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("NotebookHours5To9")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int?>("NotebookRateId")
                        .HasColumnType("integer");

                    b.HasKey("EmployeePositionId");

                    b.HasIndex("NotebookRateId");

                    b.ToTable("EmployeeWorkloads");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EnforcementDeduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EnforcementDeductions");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.NotebookRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Pct")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("SubjectKeyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NotebookRates");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<List<string>>("ExcelAliases")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<bool>("IsHourly")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkerClass")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.SickLeave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountEmployer")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("AmountFss")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("AverageDaily")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("BaseCalculationMode")
                        .HasColumnType("integer");

                    b.Property<int>("BaseDays")
                        .HasColumnType("integer");

                    b.Property<int>("BaseExcludedDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DaysEmployer")
                        .HasColumnType("integer");

                    b.Property<int>("DaysFss")
                        .HasColumnType("integer");

                    b.Property<int>("DaysTotal")
                        .HasColumnType("integer");

                    b.Property<string>("EfssNumber")
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("InsuranceSeniorityYrs")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("OverrideAmountEmployer")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("OverrideAmountFss")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("PaymentPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("WorkingDaysAbsent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SickLeaves");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.SystemParam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemParams");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.TariffGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Grade")
                        .IsUnique();

                    b.ToTable("TariffGrades");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Timesheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Advance")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("AnnualBonus")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Bonus")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Downtime")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("EnforcementOrders")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("HolidayAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Indexation")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("NightHours")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("PhysEducation")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Recalculation")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("ReplacementHours")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("UnfavorableManual")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("WorkedDays")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("WorkedHours")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("Timesheets");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.TitleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("ExcelAliases")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Pct")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("WorkerClass")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name", "WorkerClass")
                        .IsUnique();

                    b.ToTable("TitleTypes");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.TrainingLeave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageDaily")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("BaseCalculationMode")
                        .HasColumnType("integer");

                    b.Property<int>("BaseWorkingDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("InstitutionName")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("OverrideTotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("WorkingDaysAbsent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TrainingLeaves");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Vacation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AverageDaily")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("BaseAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("BaseCalculationMode")
                        .HasColumnType("integer");

                    b.Property<int?>("BaseDays")
                        .HasColumnType("integer");

                    b.Property<int>("CalendarDays")
                        .HasColumnType("integer");

                    b.Property<int?>("CarryOverMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("CarryOverYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCarryOver")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("text");

                    b.Property<decimal?>("OverrideTotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("VacationType")
                        .HasColumnType("integer");

                    b.Property<int>("WorkingDaysAbsent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Vacations");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.WorkCalendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("WorkDays")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("WorkCalendars");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Calculation", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.CalculationComponent", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Calculation", "Calculation")
                        .WithMany("Components")
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calculation");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.CalculationPeriod", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Calculation", "Calculation")
                        .WithMany("Periods")
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calculation");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeAdmin", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.EmployeePosition", "EmployeePosition")
                        .WithOne("Admin")
                        .HasForeignKey("PayrollCalc.Core.Entities.EmployeeAdmin", "EmployeePositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeePosition");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeGpd", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.EmployeePosition", "EmployeePosition")
                        .WithOne("Gpd")
                        .HasForeignKey("PayrollCalc.Core.Entities.EmployeeGpd", "EmployeePositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollCalc.Core.Entities.TariffGrade", "TariffGrade")
                        .WithMany()
                        .HasForeignKey("TariffGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmployeePosition");

                    b.Navigation("TariffGrade");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeNonPedagogical", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.EmployeePosition", "EmployeePosition")
                        .WithOne("NonPedagogical")
                        .HasForeignKey("PayrollCalc.Core.Entities.EmployeeNonPedagogical", "EmployeePositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeePosition");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeePkr", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.EmployeePosition", "EmployeePosition")
                        .WithOne("Pkr")
                        .HasForeignKey("PayrollCalc.Core.Entities.EmployeePkr", "EmployeePositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollCalc.Core.Entities.TariffGrade", "TariffGrade")
                        .WithMany()
                        .HasForeignKey("TariffGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmployeePosition");

                    b.Navigation("TariffGrade");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeePosition", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithMany("Positions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollCalc.Core.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PayrollCalc.Core.Entities.TariffGrade", "TariffGrade")
                        .WithMany()
                        .HasForeignKey("TariffGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PayrollCalc.Core.Entities.TitleType", "TitleType")
                        .WithMany()
                        .HasForeignKey("TitleTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");

                    b.Navigation("Position");

                    b.Navigation("TariffGrade");

                    b.Navigation("TitleType");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeeWorkload", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.EmployeePosition", "EmployeePosition")
                        .WithOne("Workload")
                        .HasForeignKey("PayrollCalc.Core.Entities.EmployeeWorkload", "EmployeePositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollCalc.Core.Entities.NotebookRate", "NotebookRate")
                        .WithMany()
                        .HasForeignKey("NotebookRateId");

                    b.Navigation("EmployeePosition");

                    b.Navigation("NotebookRate");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EnforcementDeduction", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Position", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.SickLeave", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Timesheet", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.TrainingLeave", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Vacation", b =>
                {
                    b.HasOne("PayrollCalc.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Calculation", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Periods");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.Employee", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("PayrollCalc.Core.Entities.EmployeePosition", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Gpd");

                    b.Navigation("NonPedagogical");

                    b.Navigation("Pkr");

                    b.Navigation("Workload");
                });
#pragma warning restore 612, 618
        }
    }
}
